ControleEstoque.Web/Models/AlterarSenhaUsuarioViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ControleEstoque.Web.Models
{
    public class AlterarSenhaUsuarioViewModel
    {
        [Required(ErrorMessage = "Preencha a senha atual.")]
        [Display (Name = "Senha Atual")]
        public string SenhaAtual { get; set; }

        [Required(ErrorMessage = "Preencha a nova senha.")]
        [MaxLength(3, ErrorMessage = "A nova senha deve ter no mínimo 3 caracteres.")]
        [Display(Name = "Nova Senha")]
        public string NovaSenha { get; set; }

        [Required(ErrorMessage = "Preencha a confirmação de nova senha.")]
        [Compare("NovaSenha", ErrorMessage = "A senha e a confirmação devem ser iguis.")]
        [Display(Name = "Confirmação da Nova Senha")]
        public string ConfirmacaoNovaSenha { get; set; }
    }
}

ControleEstoque.Web/Models/EsqueciMinhaSenhaViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ControleEstoque.Web.Models
{
    public class EsqueciMinhaSenhaViewModel
    {
        [Required(ErrorMessage = "Informe o login")]
        public string Login { get; set; }
    }
}

ControleEstoque.Web/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ControleEstoque.Web.Models
{
    public class LoginViewModel
    {
        [Required(ErrorMessage = "Informe o usuário")]
        [Display(Name = "Usúario: ")]
        public string Usuario { get; set; }

        [Required(ErrorMessage = "Informe a senha")]
        [DataType(DataType.Password)]
        [Display(Name = "Senha: ")]
        public string Senha { get; set; }


        [Display(Name = "Lembrar Me")]
        public bool LembrarMe { get; set; }
    }
}

ControleEstoque.Web/Controllers/ContaController.cs
using ControleEstoque.Web.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace ControleEstoque.Web.Controllers
{
    public class ContaController : Controller
    {
        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult Login(LoginViewModel login, string returnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View(login);
            }

            var usuario = UsuarioModel.ValidarUsuario(login.Usuario, login.Senha);

            if (usuario != null)
            {
                var ticket = FormsAuthentication.Encrypt(new FormsAuthenticationTicket(
                  1, usuario.Nome, DateTime.Now, DateTime.Now.AddHours(12), login.LembrarMe, usuario.Id + "|" + usuario.RecuperarStringNomePerfis()));/*PerfilModel.RecuperarPeloId(usuario.IdPerfil).Nome));*/
                var cookie = new HttpCookie(FormsAuthentication.FormsCookieName, ticket);
                Response.Cookies.Add(cookie);

                if (Url.IsLocalUrl(returnUrl))
                {
                    return Redirect(returnUrl);
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                ModelState.AddModelError("", "Login inválido.");
            }

            return View(login);
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult LogOff()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }

        [AllowAnonymous]
        public ActionResult AlterarSenhaUsuario(AlterarSenhaUsuarioViewModel model)
        {
            ViewBag.Mensagem = null;
            if (HttpContext.Request.HttpMethod.ToUpper() == "POST")
            {
                var usuarioLogado = (HttpContext.User as AplicacaoPrincipal);
                var alterou = false;
                if (usuarioLogado != null)
                {
                    if (!usuarioLogado.Dados.ValidarSenhaAtual(model.SenhaAtual))
                    {
                        ModelState.AddModelError("SenhaAtual", "A senha atual não confere.");
                    }
                    else
                    {
                        alterou = usuarioLogado.Dados.AlterarSalvar(model.NovaSenha);
                        if (alterou)
                        {
                            ViewBag.Mensagem = new string[] { "ok", "Senha alterada com sucesso." };
                        }
                        else
                        {
                            ViewBag.Mensagem = new string[] { "erro", "Não foi possível alterar a senha." };
                        }
                    }
                   
                }
                return View();
            }
            else {//quando for get ele simplismente não precisa mostra nenhuma msg
                ModelState.Clear();
                return View(); 
            }
            
        }

        [AllowAnonymous]
        public ActionResult EsqueciMinhaSenha(EsqueciMinhaSenhaViewModel model)
        {
            ViewBag.EmailEnviado = true;
            if (HttpContext.Request.HttpMethod.ToUpper() == "GET")
            {
                ViewBag.EmailEnviado = false;
                ModelState.Clear();
            }
            else
            {
                var usuario = UsuarioModel.RecuperarPeloIdLogin(model.Login);
                if (usuario != null)
                {
                    EnviarEmailRedefinicaoSenha(usuario);
                }
            }
            return View(model);
        }

        [AllowAnonymous]
        public ActionResult RedefinirSenha(int id)
        {
            var usuario = UsuarioModel.RecuperarPeloId(id);
            if(usuario == null)
            {
                id = -1;
            }

            var model = new NovaSenhaViewModel() { Usuario = id };

            //ViewBag.Usuario = usuario;
            ViewBag.Mensagem = null;

            return View(model);
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult RedefinirSenha(NovaSenhaViewModel model)
        {
            ViewBag.Mensagem = null;
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var usuario = UsuarioModel.RecuperarPeloId(model.Usuario);
            if (usuario != null)
            {
                var ok = usuario.AlterarSalvar(model.Senha);
                ViewBag.Mensagem = ok ? "Senha alterada com sucesso!" : "Não foi possível alterar a senha!";
            }

            return View();
        }

            private void EnviarEmailRedefinicaoSenha(UsuarioModel usuario)
        {
            var callbackUrl = Url.Action("RedefinirSenha", "conta", new { id = usuario.Id }, protocol: Request.Url.Scheme);
            var client = new SmtpClient()
            {
                Host = ConfigurationManager.AppSettings["EmailServidor"],
                Port = Convert.ToInt32(ConfigurationManager.AppSettings["EmailPorta"]),
                EnableSsl = (ConfigurationManager.AppSettings["EmailSsl"] == "S"),
                UseDefaultCredentials = false,
                DeliveryMethod = SmtpDeliveryMethod.Network,
                Credentials = new NetworkCredential(
                    ConfigurationManager.AppSettings["EmailUsuario"],
                    ConfigurationManager.AppSettings["EmailSenha"])
            };
            var mensagem = new MailMessage();
            mensagem.From = new MailAddress(ConfigurationManager.AppSettings["EmailOrigem"], "Controla de Estoque - Como Programar Melhor");
            mensagem.To.Add(usuario.Email);
            mensagem.Subject = "Redefinição de Senha";
            mensagem.Body = string.Format("Redefinição a sua senha <a href='{0}'>aqui</a>", callbackUrl);
            mensagem.IsBodyHtml = true;

            client.Send(mensagem);
        }
    }
}

ControleEstoque.Web/Views/Conta/AlterarSenhaUsuario.cshtml
@model ControleEstoque.Web.Models.AlterarSenhaUsuarioViewModel
@{
    ViewBag.Title = "Alterar Senha";
}

<style>
    .container-tela{
        width: 400px;
        margin: 0 auto;
    }
</style>

<div class="container-tela">
    <div class="row">
        <h3 class="titulo">@ViewBag.Title</h3>
    </div>
    <div class="row">
        <section>
            @using (Html.BeginForm("AlterarSenhaUsuario", "Conta", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.ValidationSummary(true, "", new { @Class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(m => m.SenhaAtual, new { @class = "control-label" })
                    @Html.PasswordFor(m => m.SenhaAtual, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.SenhaAtual, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.NovaSenha, new { @class = "control-label" })
                    @Html.PasswordFor(m => m.NovaSenha, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.NovaSenha, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.ConfirmacaoNovaSenha, new { @class = "control-label" })
                    @Html.PasswordFor(m => m.ConfirmacaoNovaSenha, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.ConfirmacaoNovaSenha, "", new { @class = "text-danger" })
                </div>

                if (ViewBag.Mensagem != null)
                {
                    if (ViewBag.Mensagem[0] == "ok")
                    {
                        <div class="alert alert-success">
                            <strong>Sucesso!</strong> @ViewBag.Mensagem[1]
                        </div>
                    }
                    else
                    {
                        <div class="alert alert-warning">
                            <strong>Aviso!</strong> @ViewBag.Mensagem[1]
                        </div>
                    }
                }

                <div class="form-group">
                    <input type="submit" class="btn btn-success" value="Alterar" />
                </div>

            }
        </section>
    </div>
</div>

@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
}

ControleEstoque.Web/Views/Conta/EsqueciMinhaSenha.cshtml
@model ControleEstoque.Web.Models.EsqueciMinhaSenhaViewModel

@{
    ViewBag.Title = "Esqueci Minha Senha";
}


<div class="container-esqueci-senha">
    <div class="row">
        <h3 class="titulo">@ViewBag.Title</h3>
    </div>
    <div class="row">
        <section>
            @using (Html.BeginForm("EsqueciMinhaSenha", "Conta", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.ValidationSummary(true, "", new { @Class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(m => m.Login, new { @class = "control-label" })
                    @Html.TextBoxFor(m => m.Login, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Login, "", new { @class = "text-danger" })
                </div>

                if (ViewBag.EmailEnviado)
                {
                        <div class="alert alert-success">
                            <strong>Sucesso!</strong> Um e-mail com o link de redefinição da sua senha foi enviado para sua caixa de e-mail.
                        </div>
                }

                <div class="form-group">
                    <input type="submit" class="btn btn-success" value="Enviar" />
                </div>

            }
        </section>
    </div>
</div>

@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
}

ControleEstoque.Web/Views/Conta/Login.cshtml
@model ControleEstoque.Web.Models.LoginViewModel
    @{
        ViewBag.Title = "Login";
    }

    <div class="container-login">
        <div class="row">
            <h3 class="titulo">Entrar no Sistema</h3>
        </div>
        <div class="row">
            <section id="loginForm">
                @using (Html.BeginForm("Login", "Conta", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                {
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(m => m.Usuario, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(m => m.Usuario, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Usuario, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Senha, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.PasswordFor(m => m.Senha, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Senha, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-4 col-md-offset-2">
                            @Html.CheckBoxFor(m => m.LembrarMe)
                            @Html.LabelFor(m => m.LembrarMe)
                        </div>

                        <div class="col-md-6" style="text-align: right">
                            @Html.ActionLink("Esqueci minha senha", "EsqueciMinhaSenha", "Conta", null, new { @class= "btn btn-primary"})
                        </div>

                    </div>
                    <div class="form-group">
                        <div class="col-md-10 col-md-offset-2">
                            <input type="submit" class="btn btn-success" value="Entrar" />
                        </div>
                    </div>
                }
            </section>
        </div>
    </div>

@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
    }

ControleEstoque.Web/Views/Conta/RedefinirSenha.cshtml
@model ControleEstoque.Web.Models.NovaSenhaViewModel

@{
    ViewBag.Title = "Redefinir Senha";
}


<div class="container-redefinir-senha">
    <div class="row">
        <h3 class="titulo">@ViewBag.Title</h3>
    </div>
    <div class="row">
        <section>
            @using (Html.BeginForm("RedefinirSenha", "Conta", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.ValidationSummary(true, "", new { @Class = "text-danger" })
                @Html.HiddenFor(m => m.Usuario)
                <div class="form-group">
                    @Html.LabelFor(m => m.Senha, new { @class = "control-label" })
                    @Html.PasswordFor(m => m.Senha, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Senha, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.ConfirmacaoSenha, new { @class = "control-label" })
                    @Html.PasswordFor(m => m.ConfirmacaoSenha, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.ConfirmacaoSenha, "", new { @class = "text-danger" })
                </div>

                if (ViewBag.Mensagem != null )
                {
                    <div class="form-group">
                        <h4>@ViewBag.Mensagem</h4>
                    </div>
                }

                <div class="form-group">
                    <input type="submit" class="btn btn-success" value="Enviar" />
                </div>

            }
        </section>
    </div>
</div>

@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
}